### ISSUE TITLE
AG grid not rendering in Foundation modal with angular2

### ISSUE THREAD

**Issue by sanjeev2315** [ceolter/ag-grid-angular-example#51]
On first load, i can see my grid is loading correctly in foundation reveal. but once i navigate and comes back to open the modal again, i can see modal size is equal to grid height but nothing displayed. Debug logs says grid initialized and loaded with data but can not see in modal. Please help, its urgent

**Comment by seanlandsman** [comment]
I'll need a plunker or similar to be able to assist you - I dont have enough to be able to help at the moment

**Comment by seanlandsman** [comment]
No repro so closing
