### ISSUE TITLE
Request: Karma Unit Test example

### ISSUE THREAD

**Issue by ciesielskico** [ceolter/ag-grid-angular-example#53]
Hi,

I spent last weekend trying to unit test my components, which contain ag-grid, but couldn't get it to work.

I tried to analyze the DOM and check if the cellFormatters format the values correctly, but the DOM of ag-grid is empty at any time during the test and I have no other idea how to check the rows for the correct format.

I'm using the latest angular-cli and testing on Chrome

Any tips or examples would be really helpful. Cheers

**Comment by seanlandsman** [comment]
Hi,

There is a working example of testing with ag-grid & karma/jasmine here: https://github.com/ceolter/ag-grid-angular-seed

I suggest you take a look and see if this points you in the right direction.

Can you please give this a go and see if it helps? Feel free to raise another issue if not

**Comment by hocine15** [comment]
The link https://github.com/ceolter/ag-grid-angular-seed is not working, Please can you update this or give a link to how to write unit test for ag-grid using jasmine karma

**Comment by aburht** [comment]
@seanlandsman seanlandsman  any update on this ?

**Comment by reihanehaf** [comment]
@hocine15  https://github.com/ShaofeiZi/ag-grid-angular-seed/tree/master/angular-cli/src/app
