### ISSUE TITLE
Cannot read property 'api' of undefined

### ISSUE THREAD

**Issue by Bhawna14** [ceolter/ag-grid-angular-example#54]
Hi,
 i am trying to use  this.gridOptions.api.setRowData(this.rowDataGrid); for updatingthe rowdata in my grid . but i am getting error as
Cannot read property 'api' of undefined

Please help.. thanks in advance

**Comment by Bhawna14** [comment]
@Sean Landsman
hey could you please help me on this.

**Comment by seanlandsman** [comment]
the api will only be available once onGridReady has been called - be sure to hold of doing anything api related until this event has been called

**Comment by ChandraTerli** [comment]
I am getting below error in prod mode, can anybody please help?
Cannot read property 'AG_GRID' of undefined

**Comment by Helmi-helmutson** [comment]
i get the same error only in prod mode 

ERROR TypeError: Cannot read property 'AG_GRID' of undefined

**Comment by ChandraTerli** [comment]
can anybody please help us please?

**Comment by bipinmangwani1** [comment]
Has anyone found any fix for "Cannot read property 'AG_GRID' of undefined" in prod mode? I've raised a new issue for this [here](https://github.com/ag-grid/ag-grid-angular/issues/220).

**Comment by khvmsk** [comment]
can anybody please help us please?

**Comment by bapuray** [comment]
Hope the below steps will help you to fix this issues. This code worked for me
1. Import - import {GridOptions} from "ag-grid-community"; in your component file
2. Declare  - @ViewChild('agGrid',{static: true}) agGrid: GridOptions; in the class
3. your HTML content should have 'agGrid' as mentioned below
<ag-grid-angular 
            #agGrid
            id="agGrid"
            row-animation
            pagination
            style="width: 800px; height: 400px;" 
            class="ag-theme-balham"
            [rowData]="rowData" 
            [columnDefs]="columnDefs"
            rowSelection="multiple"
            >
  </ag-grid-angular>

**Comment by caglarsarikaya** [comment]
this is my first help to someone else in github :) https://www.ag-grid.com/javascript-grid-api/ tis page is for ag-grid documantation and if you check you will see the what you need.
