### ISSUE TITLE
Build failure on ngtools_webpack example

### ISSUE THREAD

**Issue by poonsv** [ceolter/ag-grid-angular-example#59]
I downloaded and tried to build your **ngtools_webpack** example using npm run build:aot command.
However, it failed with the folloiwng log (I already got the latest node.js):
Am I missing anything? I really want to enable AOT on my web with angular enterprise grid:

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:aot' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prebuild:aot', 'build:aot', 'postbuild:aot' ]
5 info lifecycle ag-grid-angular-example@12.0.0~prebuild:aot: ag-grid-angular-example@12.0.0
6 silly lifecycle ag-grid-angular-example@12.0.0~prebuild:aot: no script for prebuild:aot, continuing
7 info lifecycle ag-grid-angular-example@12.0.0~build:aot: ag-grid-angular-example@12.0.0
8 verbose lifecycle ag-grid-angular-example@12.0.0~build:aot: unsafe-perm in lifecycle true
9 verbose lifecycle ag-grid-angular-example@12.0.0~build:aot: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\AMD\git\ngtools_webpack\node_modules\.bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files\Java\jdk1.8.0_65\bin;C:\Program Files\Java\jdk1.8.0_65;gram Files (x86)\CollabNet\Subversion Client;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\LINQPad4;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Collaborator Client;C:\Program Files\Microsoft\Web Platform Installer\;C:\SN Nebula;C:\cygwin64\bin;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Users\vpoon.AMD\AppData\Local\Programs\Python\Python35-32;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Mono\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\vpoon.AMD\AppData\Local\Programs\Git\cmd;C:\Program Files\Perforce;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\nodejs\;C:\Users\vpoon.AMD\.dnx\bin;C:\Program Files\Collaborator Client;C:\Users\vpoon.AMD\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\vpoon.AMD\AppData\Local\Programs\Python\Python35-32\;C:\Windows\System32;C:\cygwin64\bin;C:\Users\vpoon.AMD\AppData\Local\Microsoft\WindowsApps;C:\Users\vpoon.AMD\AppData\Roaming\npm
10 verbose lifecycle ag-grid-angular-example@12.0.0~build:aot: CWD: C:\AMD\git\ngtools_webpack
11 silly lifecycle ag-grid-angular-example@12.0.0~build:aot: Args: [ '/d /s /c',
11 silly lifecycle   'npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail' ]
12 silly lifecycle ag-grid-angular-example@12.0.0~build:aot: Returned: code: 1  signal: null
13 info lifecycle ag-grid-angular-example@12.0.0~build:aot: Failed to exec build:aot script
14 verbose stack Error: ag-grid-angular-example@12.0.0 build:aot: `npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ag-grid-angular-example@12.0.0
16 verbose cwd C:\AMD\git\ngtools_webpack
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:aot"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ag-grid-angular-example@12.0.0 build:aot: `npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail`
22 error Exit status 1
23 error Failed at the ag-grid-angular-example@12.0.0 build:aot script 'npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ag-grid-angular-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean-aot && webpack --config config/webpack.prod.aot.js --progress --profile --bail
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ag-grid-angular-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ag-grid-angular-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by seanlandsman** [comment]
This should now be fixed, thanks for reporting it.

Going forward can you please raise requests like this in the members forum (https://ag-grid.com/forum/forumdisplay.php?fid=5) as it'll get looked at much quicker

thanks
